### ISSUE TITLE
Error Issue

### ISSUE THREAD

**Issue by mikrokode** [JLFSL/FiveMultiplayer#4]
Hi Friend,

I am interested in this game, after I downloded it and tried to build it, the following error was displayed?

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1104	cannot open file 'libcef.lib'	Client.Core	C:\Users\admin\Desktop\FiveMultiplayer-dev\FiveMultiplayer-dev\FiveMultiplayer-dev\Client\Core\LINK	1	

May I know what is the problem?

**Comment by JLFSL** [comment]
Build the latest version of CEF and upgrade the current one of this repository. I should also mention that this repository is inactive.

If you wish to create your own multiplayer modification: I'd strongly discourage you to do so if you can't figure this error out on your own. Unless you're really up for it though. 

Instead, look into playing [rage.mp](http://rage.mp/), the best modification at the moment.

**Comment by mikrokode** [comment]
Friend, I have spent the whole day to check about it, because I not familiar with C++. But still unable to find the solution. I only found libcef_dll_wrapper.lib was created but did not exist any project to create libcef.lib. Where can i found the latest version of libcef.lib?

**Comment by JLFSL** [comment]
You'll have to build CEF manually: https://bitbucket.org/chromiumembedded/cef

**Comment by mikrokode** [comment]
Thanks friend, I will try it immediately, let you know later the result.

**Comment by mikrokode** [comment]
Friend,

I have downloaded the latest version of CEF from [(http://opensource.spotify.com/cefbuilds/index.html) ]
and build it with CMake and VS 2015, but the following error shown up again, I think the version problem make it could not be run, may I know which version of CEF you were using to develop it?

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in Animations.obj	Client.Core	C:\Users\admin\Desktop\Folder\a.Game Bible\FiveMultiplayer-dev\FiveMultiplayer-dev\FiveMultiplayer-dev\Client\Core\libcef_dll_wrapper.lib(libcef_dll_wrapper.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in Animations.obj	Client.Core	C:\Users\admin\Desktop\Folder\a.Game Bible\FiveMultiplayer-dev\FiveMultiplayer-dev\FiveMultiplayer-dev\Client\Core\libcef_dll_wrapper.lib(cef_logging.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in Animations.obj	Client.Core	C:\Users\admin\Desktop\Folder\a.Game Bible\FiveMultiplayer-dev\FiveMultiplayer-dev\FiveMultiplayer-dev\Client\Core\libcef_dll_wrapper.lib(app_cpptoc.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in Animations.obj	Client.Core	C:\Users\admin\Desktop\Folder\a.Game Bible\FiveMultiplayer-dev\FiveMultiplayer-dev\FiveMultiplayer-dev\Client\Core\libcef_dll_wrapper.lib(completion_callback_cpptoc.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in Animations.obj	Client.Core	C:\Users\admin\Desktop\Folder\a.Game Bible\FiveMultiplayer-dev\FiveMultiplayer-dev\FiveMultiplayer-dev\Client\Core\libcef_dll_wrapper.lib(end_tracing_callback_cpptoc.obj)	1	
Error	LNK2038	mismatch detected for 'RuntimeLibrary': value 'MTd_StaticDebug' doesn't match value 'MDd_DynamicDebug' in Animations.obj	Client.Core	C:\Users\admin\Desktop\Folder\a.Game Bible\FiveMultiplayer-dev\FiveMultiplayer-dev\FiveMultiplayer-dev\Client\Core\libcef_dll_wrapper.lib(get_geolocation_callback_cpptoc.obj)	1

**Comment by JLFSL** [comment]
I, unfortunately, do not have the time to help you with any of that in any way. My apologies.

**Comment by Hobr** [comment]
Why not search the error id?You should set the project's Runtime Library.
[https://msdn.microsoft.com/en-us/library/jj889284.aspx](https://msdn.microsoft.com/en-us/library/jj889284.aspx)

**Comment by BigETI** [comment]
If you try to staticly link a library, your build needs to be compatible with how the runtime libraries should be linked. This can be changed at `Properties -> C/C++ -> Code generation -> Runtime library`. If you dynamicly link a library, you should not have that issue at all.

**Comment by JLFSL** [comment]
I thank you kindly for helping out @BigETI.
